### ISSUE TITLE
Container doesn't apply scaling immediately?

### ISSUE THREAD

**Issue by classam** [inlet/react-pixi#147]
### Description

So, I have a Container inside a Stage. The stage has dynamic width and height (updating when I resize the page). The container has fixed width, height, and angle. 

    <Stage 
      width={width} 
      height={height} 
      options={{resolution: window.devicePixelRatio, autoDensity: true}}>
        <Container width={300} angle={45} height={300} position={[35, 10]}>
          <Sprite image="/public/img/690by540test.png" x={0} y={0}></Sprite>
        </Container>
    </Stage>

When I render this, the width and height do not trigger, and no scaling occurs: 

https://imgur.com/a/nqQ5aBp

However, if I do anything that causes the Stage to re-render (re-sizing the page does it) the Container's scaling immediately kicks in: 

https://imgur.com/a/PcOchqY

That seems... wrong, to me? I feel like I could fix it by resizing the whole container by 1px on boot, but that feels like a fudgy hack. 

### Package.json: 
    "@inlet/react-pixi": "^1.1.0",
    "pixi.js": "^5.1.2",
    "react": "^16.9.0",

    "@babel/core": "^7.6.0",
    "@babel/plugin-transform-runtime": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.6.0",
    "babelify": "^10.0.0",
    "browserify-middleware": "^8.1.1",
    "connected-react-router": "^6.5.2",
    "pixi-filters": "^3.0.3",
    "react-dom": "^16.9.0",
    "react-redux": "^7.1.1",
    "react-router": "^5.0.1",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-promise-middleware": "^6.1.1",

**Comment by inlet** [comment]
Actually this is the expected behaviour. Although you can set the `width` and `height` of a `<Container />`, it is not recommended. The dimensions are updated once a child is added, which results in the containment bounds.

You can see this in action here, go to https://pixijs.io/examples/#/demos-basic/container.js and paste this code and run it:

```js
const app = new PIXI.Application({width: 800, height: 600});
document.body.appendChild(app.view);

// Create Container
const container = new PIXI.Container();
app.stage.addChild(container);

// Update dimensions
container.width = 100;
container.height = 100;

// Create Sprite
const sp = new PIXI.Sprite();
sp.texture = PIXI.Texture.from('examples/assets/bunny.png');
container.addChild(sp);
```

The order is important.. the React reconciliation creates and updates the components in this order:

- Create/update Container
- Update/commit props to Container
- Create Sprite (child)
- Update/commit props to Sprite

I'm closing this issue now as this is the expected behaviour, please let me know if you think otherwise and why we should reopen this issue.

Thanks!
