### ISSUE TITLE
react-pixi breaks with react concurrent

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#291]
### Description
With react concurrent (0.0.0-experimental-172e89b4b built from v17.0.2), I'm getting the following error whenever I go to a page using react-pixi in components with effects

> Expected subtree parent to be a mounted class component

This is the same error as in #56.

### More context
Related to [this slack discussion](https://app.slack.com/client/TRTCSS69L/CRT2JTG3Z).
I have a component that needs 2 seconds to render 20 thousand children (rendering a game map). 
I tried to render a loading animation on the canvas while the map is rendering as hidden, but the task is blocking, my loading animation is stuck on a frame for the whole 2 seconds.
This is why I tried to return to React concurrent, which will interrupt slow tasks and simulate parallel execution of differennt tasks, allowing my loading animation to play while the map is building.

### Steps to reproduce
https://codesandbox.io/s/gifted-thunder-6nqhx

### Additional info
versions in sandbox

**Comment by inlet** [comment]
This is an expected behaviour. react-pixi uses fb's `react-reconciler@latest`. 
Once the react concurrent version (0.0.0-exp...) will be merged into the stable (latest) release, I can update this lib accordingly.

I'll close this issue for now. If you like you can create a PR where you use the experimental `react-reconciler@0.0.0-172e89b4b` and implement the concurrent details for react-pixi.
