### ISSUE TITLE
Integrating React-pixi with Meteor-React

### ISSUE THREAD

**Issue by ashlite** [inlet/react-pixi#293]
So I build a meteor-react app for a simple game and add react-pixi to it. React-pixi v6.5.0, react v17, pixi v6, meteorjs.
I tried following the documentation, and try with the simple stage component. Then I get this error
![image](https://user-images.githubusercontent.com/78148802/115024667-98525300-9eea-11eb-8b8c-e1c9fcf283bb.png)
There is no other react-pixi component I use for now because I can’t fix this error.
And it seems that there is a conflict between meteorJS middleware and pixijs. But I don't know anymore.

**Comment by inlet** [comment]
Hi @ashlite could you create a codesandbox example?

**Comment by ashlite** [comment]
I don't have codesandbox for now.
You can easily duplicate this by creating meteor-react project base on this doc https://react-tutorial.meteor.com/simple-todos/01-creating-app.html

then just change the App.jsx in imports/ui
```
import React from 'react'
import { Stage, Sprite } from '@inlet/react-pixi'

export const App = () => (
  <div>
    <Stage width={800} height={800}>
      <Sprite image="https://via.placeholder.com/300/FF0000" x={100} y={100} />
    </Stage>
  </div>
)
```

Try it using fresh install meteor js + react-pixi + pixi.js

**Comment by inlet** [comment]
I have not installed Meteor on my local machine, so I cannot test it here.. but regarding to the error message it looks like you're not using the latest React version (v17.0.2). 

The react-reconciler package is considered experimental and changes over time, that's why the latest version of react-pixi is always in sync with the latest version of React.

To use an older react-reconciler implementation in react-pixi you could try to downgrade `@inlet/react-pixi` to `v6.3.0`:

```
npm install @inlet/react-pixi@6.3.0
```

See [Releases](https://github.com/inlet/react-pixi/releases) and search for react-reconciler updates if you'd like to downgrade even further.

**Comment by ashlite** [comment]
default meteor create will adding react v16
But even though I install the latest react version (v17), it still producing the same error.
