### ISSUE TITLE
Create support for a Gif component

### ISSUE THREAD

**Issue by afogel** [inlet/react-pixi#321]
### Description

Hi @inlet , Thanks again for this amazing library. I was wondering -- would you be open to supporting pixi plugins as native component? Or is this something that you'd suggest individual projects develop for themselves using [custom components](https://reactpixi.org/custom-components)?

If you're open to it, I'm interested in contributing to build a react-pixi component that supports gifs [(a recently added plugin](https://github.com/pixijs/gif)). If I were to contribute, are there particular considerations I need to take into consideration, or should I try to get it to look as much as possible like the Sprite component.
Thanks!

**Comment by inlet** [comment]
Hi Ariel,

Thank you for reaching out!

So to answer your question, in order to keep the footprint as small as possible I believe it's best to separate add-ons like these from the core. 

Basically the custom components are built for these kind of add-ons, giving users the power to tap into the React reconciliation with custom written logic. But maybe you've another idea how this should work, could you tell me how we can improve this library in order to support a more streamlined implementation of plugins?

Thanks!
